### ISSUE TITLE
Addon übersetzen

### ISSUE THREAD

**Issue by alexplusde** [alexplusde/yform_spam_protection#2]
Lang-Dateien hinzufügen und Strings dorthin auslagern.

**Comment by 191977** [comment]
Hi,
ich mach mich da mal, vielleicht ganz gutes Thema um da bisschen reinzukommen...
Micha

**Comment by alexplusde** [comment]
Prima, danke! Für Sprachen und für Änderungen an den Einstellungen würde man im besten Fall zwei getrennte PRs anlegen, aber für den Anfang ist das vollkommen okay. Ich teste die Änderungen und veröffentliche dann zeitnah die 1.0.6
